# Generated by Django 5.0.3 on 2024-03-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
                ('machine_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
